[package]
name = "algoPlayground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "grokking_algorithms"

[dependencies]
rand = "0.8.5"